// For this project development
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  // GlobalComponents for Volar
  export interface GlobalComponents {
    EhAffix: typeof import('../packages/ehop')['EhAffix']
    EhAlert: typeof import('../packages/ehop')['EhAlert']
    EhAside: typeof import('../packages/ehop')['EhAside']
    EhAutocomplete: typeof import('../packages/ehop')['EhAutocomplete']
    EhAvatar: typeof import('../packages/ehop')['EhAvatar']
    EhBacktop: typeof import('../packages/ehop')['EhBacktop']
    EhBadge: typeof import('../packages/ehop')['EhBadge']
    EhBreadcrumb: typeof import('../packages/ehop')['EhBreadcrumb']
    EhBreadcrumbItem: typeof import('../packages/ehop')['EhBreadcrumbItem']
    EhButton: typeof import('../packages/ehop')['EhButton']
    EhButtonGroup: typeof import('../packages/ehop')['EhButtonGroup']
    EhCalendar: typeof import('../packages/ehop')['EhCalendar']
    EhCard: typeof import('../packages/ehop')['EhCard']
    EhCarousel: typeof import('../packages/ehop')['EhCarousel']
    EhCarouselItem: typeof import('../packages/ehop')['EhCarouselItem']
    EhCascader: typeof import('../packages/ehop')['EhCascader']
    EhCascaderPanel: typeof import('../packages/ehop')['EhCascaderPanel']
    EhCheckbox: typeof import('../packages/ehop')['EhCheckbox']
    EhCheckboxButton: typeof import('../packages/ehop')['EhCheckboxButton']
    EhCheckboxGroup: typeof import('../packages/ehop')['EhCheckboxGroup']
    EhCol: typeof import('../packages/ehop')['EhCol']
    EhCollapse: typeof import('../packages/ehop')['EhCollapse']
    EhCollapseItem: typeof import('../packages/ehop')['EhCollapseItem']
    EhCollapseTransition: typeof import('../packages/ehop')['EhCollapseTransition']
    EhColorPicker: typeof import('../packages/ehop')['EhColorPicker']
    EhContainer: typeof import('../packages/ehop')['EhContainer']
    EhConfigProvider: typeof import('../packages/ehop')['EhConfigProvider']
    EhDatePicker: typeof import('../packages/ehop')['EhDatePicker']
    EhDialog: typeof import('../packages/ehop')['EhDialog']
    EhDivider: typeof import('../packages/ehop')['EhDivider']
    EhDrawer: typeof import('../packages/ehop')['EhDrawer']
    EhDropdown: typeof import('../packages/ehop')['EhDropdown']
    EhDropdownItem: typeof import('../packages/ehop')['EhDropdownItem']
    EhDropdownMenu: typeof import('../packages/ehop')['EhDropdownMenu']
    EhEmpty: typeof import('../packages/ehop')['EhEmpty']
    EhFooter: typeof import('../packages/ehop')['EhFooter']
    EhForm: typeof import('../packages/ehop')['EhForm']
    EhFormItem: typeof import('../packages/ehop')['EhFormItem']
    EhHeader: typeof import('../packages/ehop')['EhHeader']
    EhIcon: typeof import('../packages/ehop')['EhIcon']
    EhImage: typeof import('../packages/ehop')['EhImage']
    EhImageViewer: typeof import('../packages/ehop')['EhImageViewer']
    EhInput: typeof import('../packages/ehop')['EhInput']
    EhInputNumber: typeof import('../packages/ehop')['EhInputNumber']
    EhLink: typeof import('../packages/ehop')['EhLink']
    EhMain: typeof import('../packages/ehop')['EhMain']
    EhMenu: typeof import('../packages/ehop')['EhMenu']
    EhMenuItem: typeof import('../packages/ehop')['EhMenuItem']
    EhMenuItemGroup: typeof import('../packages/ehop')['EhMenuItemGroup']
    EhOption: typeof import('../packages/ehop')['EhOption']
    EhOptionGroup: typeof import('../packages/ehop')['EhOptionGroup']
    EhPageHeader: typeof import('../packages/ehop')['EhPageHeader']
    EhPagination: typeof import('../packages/ehop')['EhPagination']
    EhPopconfirm: typeof import('../packages/ehop')['EhPopconfirm']
    EhPopper: typeof import('../packages/ehop')['EhPopper']
    EhProgress: typeof import('../packages/ehop')['EhProgress']
    EhRadio: typeof import('../packages/ehop')['EhRadio']
    EhRadioButton: typeof import('../packages/ehop')['EhRadioButton']
    EhRadioGroup: typeof import('../packages/ehop')['EhRadioGroup']
    EhRate: typeof import('../packages/ehop')['EhRate']
    EhRow: typeof import('../packages/ehop')['EhRow']
    EhScrollbar: typeof import('../packages/ehop')['EhScrollbar']
    EhSelect: typeof import('../packages/ehop')['EhSelect']
    EhSlider: typeof import('../packages/ehop')['EhSlider']
    EhStep: typeof import('../packages/ehop')['EhStep']
    EhSteps: typeof import('../packages/ehop')['EhSteps']
    EhSubMenu: typeof import('../packages/ehop')['EhSubMenu']
    EhSwitch: typeof import('../packages/ehop')['EhSwitch']
    EhTabPane: typeof import('../packages/ehop')['EhTabPane']
    EhTable: typeof import('../packages/ehop')['EhTable']
    EhTableColumn: typeof import('../packages/ehop')['EhTableColumn']
    EhTabs: typeof import('../packages/ehop')['EhTabs']
    EhTag: typeof import('../packages/ehop')['EhTag']
    EhText: typeof import('../packages/ehop')['EhText']
    EhTimePicker: typeof import('../packages/ehop')['EhTimePicker']
    EhTimeSelect: typeof import('../packages/ehop')['EhTimeSelect']
    EhTimeline: typeof import('../packages/ehop')['EhTimeline']
    EhTimelineItem: typeof import('../packages/ehop')['EhTimelineItem']
    EhTooltip: typeof import('../packages/ehop')['EhTooltip']
    EhTransfer: typeof import('../packages/ehop')['EhTransfer']
    EhTree: typeof import('../packages/ehop')['EhTree']
    EhTreeSelect: typeof import('../packages/ehop')['EhTreeSelect']
    EhTreeV2: typeof import('../packages/ehop')['EhTreeV2']
    EhUpload: typeof import('../packages/ehop')['EhUpload']
    EhSpace: typeof import('../packages/ehop')['EhSpace']
    EhSkeleton: typeof import('../packages/ehop')['EhSkeleton']
    EhSkeletonItem: typeof import('../packages/ehop')['EhSkeletonItem']
    EhStatistic: typeof import('../packages/ehop')['EhStatistic']
    EhCheckTag: typeof import('../packages/ehop')['EhCheckTag']
    EhDescriptions: typeof import('../packages/ehop')['EhDescriptions']
    EhDescriptionsItem: typeof import('../packages/ehop')['EhDescriptionsItem']
    EhResult: typeof import('../packages/ehop')['EhResult']
    EhSelectV2: typeof import('../packages/ehop')['EhSelectV2']
  }

  interface ComponentCustomProperties {
    $message: typeof import('../packages/ehop')['EhMessage']
    $notify: typeof import('../packages/ehop')['EhNotification']
    $msgbox: typeof import('../packages/ehop')['EhMessageBox']
    $messageBox: typeof import('../packages/ehop')['EhMessageBox']
    $alert: typeof import('../packages/ehop')['EhMessageBox']['alert']
    $confirm: typeof import('../packages/ehop')['EhMessageBox']['confirm']
    $prompt: typeof import('../packages/ehop')['EhMessageBox']['prompt']
    $loading: typeof import('../packages/ehop')['EhLoadingService']
  }
}

export {}
