// For this project development
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  // GlobalComponents for Volar
  export interface GlobalComponents {
    ElAffix: typeof import('../packages/ehop')['ElAffix']
    ElAlert: typeof import('../packages/ehop')['ElAlert']
    ElAside: typeof import('../packages/ehop')['ElAside']
    ElAutocomplete: typeof import('../packages/ehop')['ElAutocomplete']
    ElAvatar: typeof import('../packages/ehop')['ElAvatar']
    ElBacktop: typeof import('../packages/ehop')['ElBacktop']
    ElBadge: typeof import('../packages/ehop')['ElBadge']
    ElBreadcrumb: typeof import('../packages/ehop')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('../packages/ehop')['ElBreadcrumbItem']
    ElButton: typeof import('../packages/ehop')['ElButton']
    ElButtonGroup: typeof import('../packages/ehop')['ElButtonGroup']
    ElCalendar: typeof import('../packages/ehop')['ElCalendar']
    ElCard: typeof import('../packages/ehop')['ElCard']
    ElCarousel: typeof import('../packages/ehop')['ElCarousel']
    ElCarouselItem: typeof import('../packages/ehop')['ElCarouselItem']
    ElCascader: typeof import('../packages/ehop')['ElCascader']
    ElCascaderPanel: typeof import('../packages/ehop')['ElCascaderPanel']
    ElCheckbox: typeof import('../packages/ehop')['ElCheckbox']
    ElCheckboxButton: typeof import('../packages/ehop')['ElCheckboxButton']
    ElCheckboxGroup: typeof import('../packages/ehop')['ElCheckboxGroup']
    ElCol: typeof import('../packages/ehop')['ElCol']
    ElCollapse: typeof import('../packages/ehop')['ElCollapse']
    ElCollapseItem: typeof import('../packages/ehop')['ElCollapseItem']
    ElCollapseTransition: typeof import('../packages/ehop')['ElCollapseTransition']
    ElColorPicker: typeof import('../packages/ehop')['ElColorPicker']
    ElContainer: typeof import('../packages/ehop')['ElContainer']
    ElConfigProvider: typeof import('../packages/ehop')['ElConfigProvider']
    ElDatePicker: typeof import('../packages/ehop')['ElDatePicker']
    ElDialog: typeof import('../packages/ehop')['ElDialog']
    ElDivider: typeof import('../packages/ehop')['ElDivider']
    ElDrawer: typeof import('../packages/ehop')['ElDrawer']
    ElDropdown: typeof import('../packages/ehop')['ElDropdown']
    ElDropdownItem: typeof import('../packages/ehop')['ElDropdownItem']
    ElDropdownMenu: typeof import('../packages/ehop')['ElDropdownMenu']
    ElEmpty: typeof import('../packages/ehop')['ElEmpty']
    ElFooter: typeof import('../packages/ehop')['ElFooter']
    ElForm: typeof import('../packages/ehop')['ElForm']
    ElFormItem: typeof import('../packages/ehop')['ElFormItem']
    ElHeader: typeof import('../packages/ehop')['ElHeader']
    ElIcon: typeof import('../packages/ehop')['ElIcon']
    ElImage: typeof import('../packages/ehop')['ElImage']
    ElImageViewer: typeof import('../packages/ehop')['ElImageViewer']
    ElInput: typeof import('../packages/ehop')['ElInput']
    ElInputNumber: typeof import('../packages/ehop')['ElInputNumber']
    ElLink: typeof import('../packages/ehop')['ElLink']
    ElMain: typeof import('../packages/ehop')['ElMain']
    ElMenu: typeof import('../packages/ehop')['ElMenu']
    ElMenuItem: typeof import('../packages/ehop')['ElMenuItem']
    ElMenuItemGroup: typeof import('../packages/ehop')['ElMenuItemGroup']
    ElOption: typeof import('../packages/ehop')['ElOption']
    ElOptionGroup: typeof import('../packages/ehop')['ElOptionGroup']
    ElPageHeader: typeof import('../packages/ehop')['ElPageHeader']
    ElPagination: typeof import('../packages/ehop')['ElPagination']
    ElPopconfirm: typeof import('../packages/ehop')['ElPopconfirm']
    ElPopper: typeof import('../packages/ehop')['ElPopper']
    ElProgress: typeof import('../packages/ehop')['ElProgress']
    ElRadio: typeof import('../packages/ehop')['ElRadio']
    ElRadioButton: typeof import('../packages/ehop')['ElRadioButton']
    ElRadioGroup: typeof import('../packages/ehop')['ElRadioGroup']
    ElRate: typeof import('../packages/ehop')['ElRate']
    ElRow: typeof import('../packages/ehop')['ElRow']
    ElScrollbar: typeof import('../packages/ehop')['ElScrollbar']
    ElSelect: typeof import('../packages/ehop')['ElSelect']
    ElSlider: typeof import('../packages/ehop')['ElSlider']
    ElStep: typeof import('../packages/ehop')['ElStep']
    ElSteps: typeof import('../packages/ehop')['ElSteps']
    ElSubMenu: typeof import('../packages/ehop')['ElSubMenu']
    ElSwitch: typeof import('../packages/ehop')['ElSwitch']
    ElTabPane: typeof import('../packages/ehop')['ElTabPane']
    ElTable: typeof import('../packages/ehop')['ElTable']
    ElTableColumn: typeof import('../packages/ehop')['ElTableColumn']
    ElTabs: typeof import('../packages/ehop')['ElTabs']
    ElTag: typeof import('../packages/ehop')['ElTag']
    ElText: typeof import('../packages/ehop')['ElText']
    ElTimePicker: typeof import('../packages/ehop')['ElTimePicker']
    ElTimeSelect: typeof import('../packages/ehop')['ElTimeSelect']
    ElTimeline: typeof import('../packages/ehop')['ElTimeline']
    ElTimelineItem: typeof import('../packages/ehop')['ElTimelineItem']
    ElTooltip: typeof import('../packages/ehop')['ElTooltip']
    ElTransfer: typeof import('../packages/ehop')['ElTransfer']
    ElTree: typeof import('../packages/ehop')['ElTree']
    ElTreeSelect: typeof import('../packages/ehop')['ElTreeSelect']
    ElTreeV2: typeof import('../packages/ehop')['ElTreeV2']
    ElUpload: typeof import('../packages/ehop')['ElUpload']
    ElSpace: typeof import('../packages/ehop')['ElSpace']
    ElSkeleton: typeof import('../packages/ehop')['ElSkeleton']
    ElSkeletonItem: typeof import('../packages/ehop')['ElSkeletonItem']
    ElStatistic: typeof import('../packages/ehop')['ElStatistic']
    ElCheckTag: typeof import('../packages/ehop')['ElCheckTag']
    ElDescriptions: typeof import('../packages/ehop')['ElDescriptions']
    ElDescriptionsItem: typeof import('../packages/ehop')['ElDescriptionsItem']
    ElResult: typeof import('../packages/ehop')['ElResult']
    ElSelectV2: typeof import('../packages/ehop')['ElSelectV2']
  }

  interface ComponentCustomProperties {
    $message: typeof import('../packages/ehop')['ElMessage']
    $notify: typeof import('../packages/ehop')['ElNotification']
    $msgbox: typeof import('../packages/ehop')['ElMessageBox']
    $messageBox: typeof import('../packages/ehop')['ElMessageBox']
    $alert: typeof import('../packages/ehop')['ElMessageBox']['alert']
    $confirm: typeof import('../packages/ehop')['ElMessageBox']['confirm']
    $prompt: typeof import('../packages/ehop')['ElMessageBox']['prompt']
    $loading: typeof import('../packages/ehop')['ElLoadingService']
  }
}

export {}
